name: Generate Snake Animation

on:
  schedule:
    - cron: "* */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    name: Generate contribution snake
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: ErickQuintao
          gif_out_path: dist/github-contribution-grid-snake.gif

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
