name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate contribution snake
    runs-on: ubuntu-latest
    steps:
      # ⬇️ Checkout é necessário!
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake GIF
        uses: Platane/snk@master
        with:
          github_user_name: ErickQuintao
          gif_out_path: dist/github-contribution-grid-snake.gif

      - name: Publish snake animation to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
